Install `netbase` in Docker
TCP connections were unable to be made, and logs were being spammed with:
    Exception: FailedConnectionException2 "ct.googleapis.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)

The fix is to install `netbase`, which provides `/etc/protocols`. See https://github.com/bos/wreq/issues/5#issuecomment-136216608 for context.